### ISSUE TITLE
reload causes segfault

### ISSUE THREAD

**Issue by dangowrt** [arkap/netifd#1]
netifd segfaults on reload, even though no changes to configuration have been (it's the sample from ovsd Readme.md) made:
```
Program received signal SIGSEGV, Segmentation fault.
blob_len (attr=attr@entry=0x7)
    at /usr/src/lede/staging_dir/target-x86_64_musl/usr/include/libubox/blob.h:102
102     /usr/src/lede/staging_dir/target-x86_64_musl/usr/include/libubox/blob.h: No such file or directory.
(gdb)
(gdb) bt
#0  blob_len (attr=attr@entry=0x7)
    at /usr/src/lede/staging_dir/target-x86_64_musl/usr/include/libubox/blob.h:102
#1  0x00007ffff7f6b0f3 in uci_blob_diff (tb1=0x7fffffffe780,
    tb2=0x7fffffffe790, config=<optimized out>, diff=0x7fffffffe778)
    at /usr/src/lede/build_dir/target-x86_64_musl/uci-2020-04-24-ec8d3233/blob.c:180
#2  0x0000000000408f12 in ubusdev_bridge_reload (dev=dev@entry=0x7ffff7f6f2c0,
    config=0x7ffff7f4c440, config@entry=0x7ffff7f41c20)
    at /usr/src/lede/build_dir/target-x86_64_musl/netifd-2020-10-08-64ff9093/ubusdev.c:667
#3  0x0000000000408fd2 in ubusdev_reload (dev=0x7ffff7f6f2c0,
    config=0x7ffff7f41c20)
    at /usr/src/lede/build_dir/target-x86_64_musl/netifd-2020-10-08-64ff9093/ubusdev.c:743
#4  0x00000000004147aa in device_set_config (attr=attr@entry=0x7ffff7f41c20,
    type=type@entry=0x7ffff7f41c20, dev=dev@entry=0x7ffff7f6f2c0)
    at /usr/src/lede/build_dir/target-x86_64_musl/netifd-2020-10-08-64ff9093/device.c:827
#5  device_apply_config (dev=dev@entry=0x7ffff7f6f2c0,
    type=type@entry=0x7ffff7f78600, config=config@entry=0x7ffff7f41c20)
    at /usr/src/lede/build_dir/target-x86_64_musl/netifd-2020-10-08-64ff9093/device.c:851
...
```

**Comment by arkap** [comment]
9fff8f5 should fix this (and also improve the reload mechanism overall).
